# Generated by Django 5.1.6 on 2025-02-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexporiahome', '0003_ai_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Eroor 404', max_length=255)),
                ('imagee', models.ImageField(default='error 404', upload_to='images/')),
                ('descrip', models.TextField(default='error 404')),
            ],
        ),
    ]
