# Generated by Django 5.1.6 on 2025-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexporiahome', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='indianAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='error 404', max_length=255)),
                ('description', models.TextField(default='error 404')),
                ('category', models.TextField(default='error 404')),
                ('image', models.ImageField(default='error 404', upload_to='images/')),
                ('url', models.URLField(default='error 404')),
            ],
        ),
    ]
