# Generated by Django 5.1.6 on 2025-02-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexporiahome', '0005_indianai'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
