# Generated by Django 5.1.6 on 2025-02-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexporiahome', '0006_ai_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='indianai',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
