# Generated by Django 5.1.6 on 2025-02-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexporiahome', '0007_indianai_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIToolAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='aiexporiahome.ai')),
            ],
        ),
        migrations.CreateModel(
            name='AIToolDisadvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disadvantages', to='aiexporiahome.ai')),
            ],
        ),
        migrations.CreateModel(
            name='AIToolRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='aiexporiahome.ai')),
            ],
        ),
    ]
