# Generated by Django 5.1.6 on 2025-02-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexporiahome', '0008_aitooladvantage_aitooldisadvantage_aitoolrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitooladvantage',
            name='text',
            field=models.TextField(default='error'),
        ),
        migrations.AlterField(
            model_name='aitooladvantage',
            name='tool',
            field=models.ForeignKey(default='error', on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='aiexporiahome.ai'),
        ),
        migrations.AlterField(
            model_name='aitooldisadvantage',
            name='text',
            field=models.TextField(default='error'),
        ),
        migrations.AlterField(
            model_name='aitooldisadvantage',
            name='tool',
            field=models.ForeignKey(default='error', on_delete=django.db.models.deletion.CASCADE, related_name='disadvantages', to='aiexporiahome.ai'),
        ),
        migrations.AlterField(
            model_name='aitoolrating',
            name='parameter',
            field=models.CharField(default='error', max_length=255),
        ),
        migrations.AlterField(
            model_name='aitoolrating',
            name='rating',
            field=models.IntegerField(default='error'),
        ),
        migrations.AlterField(
            model_name='aitoolrating',
            name='tool',
            field=models.ForeignKey(default='Error', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='aiexporiahome.ai'),
        ),
    ]
