# Generated by Django 5.1.6 on 2025-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexporiahome', '0009_alter_aitooladvantage_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='image',
            field=models.ImageField(default='error 404', upload_to='s3://shaurya-bucket-5763394/admin/img/'),
        ),
    ]
